In [194]:
#데이타 = [(0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (2.0, 1.0)]
#Approximater -> f(x; w0, w1, w2) = w2*x^2 + w1*x + w0
#learning_rate = 0.05
#w0, w1, w2는 random하게 초기화
import numpy as np

x = [0.0, 1.0, 1.0, 2.0]
y = [0.0, 1.0, 2.0, 1.0]
w = [np.random.rand(), np.random.rand(), np.random.rand()]
lr = 0.005
for i in range(5000):
    gw0, gw1, gw2 = 0, 0, 0
    for j in range(len(x)):
        fx = w[2] * x[j] ** 2 + w[1] * x[j] + w[0]
        gw0 += -2 * (y[j] - fx)
        gw1 += -2 * (y[j] - fx) * x[j]
        gw2 += -2 * (y[j] - fx) * x[j] ** 2
        # print(gw0, gw1, gw2)
    if i % 100 == 0:
        print("{}회, w0 : {}, w1 : {}, w2 : {}".format(i + 1, w[0], w[1], w[2]))
    w[0] = w[0] - lr * gw0
    w[1] = w[1] - lr * gw1
    w[2] = w[2] - lr * gw2

print("모델모형은 : f(x) = {}x^2 + {}x + {}".format("%.3f" % w[2], "%.3f" % w[1], "%.3f" % w[0]))

1회, w0 : 0.4568216510463935, w1 : 0.5211405102907869, w2 : 0.6725897159350313
101회, w0 : 0.5679114567628284, w1 : 0.6453306456332086, w2 : -0.1476208951647647
201회, w0 : 0.5329477482577926, w1 : 0.9420149194453831, w2 : -0.30504394934757734
301회, w0 : 0.4584813841137178, w1 : 1.1859174557001273, w2 : -0.4172202622607869
401회, w0 : 0.388436977727617, w1 : 1.3907830729440316, w2 : -0.5086159777450362
501회, w0 : 0.328156204188171, w1 : 1.5635736481056164, w2 : -0.5852486199155366
601회, w0 : 0.2770811554130367, w1 : 1.7094256203728464, w2 : -0.6498615018276255
701회, w0 : 0.23393176128009746, w1 : 1.8325571130731553, w2 : -0.7043975652068238
801회, w0 : 0.19749815342487656, w1 : 1.9365103930509224, w2 : -0.7504375749208128
901회, w0 : 0.16673827677240202, w1 : 2.024273008900568, w2 : -0.7893065843174135
1001회, w0 : 0.14076908234201752, w1 : 2.0983667218572006, w2 : -0.822121753548274
1101회, w0 : 0.1188445289827586, w1 : 2.1609204560493023, w2 : -0.8498260044817619
1201회, w0 : 0.10033468633029

In [147]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W1"] = np.array([[-0.089, 0.098], [0.028, -0.07]])
    network["b1"] = np.array([0.092, -0.01])
    network["W2"] = np.array([0.056, 0.067])
    network["b2"] = np.array([0.016])
    
    return network

def model(x, network):
    W1, W2 = network["W1"], network["W2"]
    b1, b2 = network["b1"], network["b2"]
    
    net1 = np.dot(x, W1) + b1
    print("net1", np.round(net1, 3))
    h1 = sigmoid(net1)
    print("h1", np.round(h1, 3))
    net2 = np.dot(h1, W2) + b2
    print("net2", np.round(net2, 3))
    h2 = sigmoid(net2)
    o2 = h2
    print("o2", np.round(o2, 3))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W1, W2 = network["W1"], network["W2"]
    b1, b2 = network["b1"], network["b2"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    
    for i in range(len(X)):
        del_W2 = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
        #del_b2 = 
        print(del_W2)
    
    
    return net1
    

In [148]:
X = np.array([[1.0, 1.0], [1.0, 0.0], [0.0, 1.0], [0.0, 0.0]])
Y = np.array([0, 1, 1, 0])
network = init_network()

In [149]:
model = model(X, network)

net1 [[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
h1 [[0.508 0.504]
 [0.501 0.522]
 [0.53  0.48 ]
 [0.523 0.498]]
net2 [0.078 0.079 0.078 0.079]
o2 [0.52  0.52  0.519 0.52 ]


In [150]:
bac = backPropa(model, network)

[0.06584934 0.06542792]
[-0.06002837 -0.06257405]
[-0.06357223 -0.05758004]
[0.06783657 0.06453105]


In [218]:
print(bac)

[[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]


In [144]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07], [0.092, -0.01]])
    network["V"] = np.array([0.056, 0.067, 0.016])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    print(W, V)
    
    net1 = np.dot(x, W)
    print("net1", np.round(net1, 4))
    h1 = sigmoid(net1)
    print("h1", np.round(h1, 4))
    w = np.array([1.0, 1.0, 1.0, 1.0])
    w = w.reshape(-1,1)
    h1 = np.hstack((h1, w))
    print("h1 ver1", h1)
    net2 = np.dot(h1, V)
    print("net2", np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    print("o2", np.round(o2, 4))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    print("V가중치", V)
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    delta_V = []
    delta_W = []
    #print("E/w1, E/w2, E/w3")
    sum_EV_0, sum_EV_1, sum_EV_2  = 0, 0, 0
    for i in range(len(X)):
        del_V = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
        #print(np.round(del_W2[2], 4), np.round(del_W2[1], 4), np.round(del_W2[0], 4))
        print(del_V)
        sum_EV_0 += del_V[0]
        sum_EV_1 += del_V[1]
        sum_EV_2 += del_V[2]
        
        del_W = (Y[i]-o2[i])*o2[i]*(1-o2[i])
        
        print("del_W", del_W)
        print("V", V[i])
        #del_W1 = -X[i]*h1[i]*(1-h1[i])*sum_W1
        #delta_W2.append(del_W2)
        #delta_W1.append(del_W1)
    
    print(np.round(sum_EV_0, 4), np.round(sum_EV_1, 4), np.round(sum_EV_2, 4))
    #print(delta_W1)

X = np.array([[1.0, 1.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [0.0, 0.0, 1.0]])
Y = np.array([0, 1, 1, 0])

In [145]:
network = init_network()

In [146]:
model = model(X, network)

[[-0.089  0.098]
 [ 0.028 -0.07 ]
 [ 0.092 -0.01 ]] [0.056 0.067 0.016]
net1 [[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
h1 [[0.5077 0.5045]
 [0.5007 0.522 ]
 [0.53   0.48  ]
 [0.523  0.4975]]
h1 ver1 [[0.50774938 0.50449988 1.        ]
 [0.50075    0.52198581 1.        ]
 [0.52996405 0.48001066 1.        ]
 [0.52298379 0.49750002 1.        ]]
net2 [0.0782 0.079  0.0778 0.0786]
o2 [0.5195 0.5197 0.5194 0.5196]


In [140]:
bac = backPropa(model, network)

V가중치 [0.056 0.067 0.016]
[0.06584934 0.06542792 0.12968867]
del_W -0.12968867309834645
V 0.056
[-0.06002837 -0.06257405 -0.11987692]
del_W 0.11987692058020538
V 0.067
[-0.06357223 -0.05758004 -0.11995575]
del_W 0.11995574538880055
V 0.016
[0.06783657 0.06453105 0.12971066]
del_W -0.12971065520787498


IndexError: index 3 is out of bounds for axis 0 with size 3

In [159]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07]])
    network["b_W"] = np.array([[0.092, -0.01]])
    network["V"] = np.array([[0.056], [0.067]])
    network["b_V"] = np.array([[0.016]])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    
    net1 = np.dot(x, W) + b_W
    print("net1", np.round(net1, 4))
    h1 = sigmoid(net1)
    print("h1", np.round(h1, 4))
    net2 = np.dot(h1, V) + b_V
    print("net2", np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    print("o2", np.round(o2, 3))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    
    for i in range(len(X)):
        d_o2 = -(Y[i] - o2[i]) * o2[i] * (1 - o2[i])
        print("d_o2", d_o2[i])

    error_hidden_layer = d_o2.dot(V.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(h1)
    print("d_hidden_layer", d_hidden_layer)
    '''
    W1, W2 = network["W1"], network["W2"]
    b1, b2 = network["b1"], network["b2"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    
    for i in range(len(X)):
        del_W2 = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
        #del_b2 = 
        print(del_W2)
    '''    
    return net1

X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])
network = init_network()    

In [160]:
model = model(X, network)

net1 [[ 0.092 -0.01 ]
 [ 0.12  -0.08 ]
 [ 0.003  0.088]
 [ 0.031  0.018]]
h1 [[0.523  0.4975]
 [0.53   0.48  ]
 [0.5007 0.522 ]
 [0.5077 0.5045]]
net2 [[0.0786]
 [0.0778]
 [0.079 ]
 [0.0782]]
o2 [[0.52 ]
 [0.519]
 [0.52 ]
 [0.52 ]]


In [161]:
bac = backPropa(model, network)

d_o2 0.12971065520787498


IndexError: index 1 is out of bounds for axis 0 with size 1

In [241]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07], [0.092, -0.01]])
    network["V"] = np.array([0.056, 0.067, 0.016])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    #print(W, V)
    
    net1 = np.dot(x, W)
    print(" <<net1>>")
    print(np.round(net1, 4))
    h1 = sigmoid(net1)
    print(" <<h1>>")
    print(np.round(h1, 4))
    w = np.array([1.0, 1.0, 1.0, 1.0])
    w = w.reshape(-1,1)
    h1 = np.hstack((h1, w))
    net2 = np.dot(h1, V)
    print(" <<net2>>")
    print(np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    print(" <<o2>>")
    print(np.round(o2, 4))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    #print("V가중치", V)
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    delta_V = []
    delta_W = []
    #print("E/w1, E/w2, E/w3")
    sum_EV_0, sum_EV_1, sum_EV_2  = 0, 0, 0
    for _ in range(len(X)):
        print("dE/dW13", "dE/dW12", "dE/dW11")
        for i in range(4):
            del_V = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
            #print(np.round(del_W2[2], 4), np.round(del_W2[1], 4), np.round(del_W2[0], 4))
            
            print(np.round(del_V[2],4), np.round(del_V[1], 4), np.round(del_V[0], 4))
            sum_EV_0 += del_V[0]
            sum_EV_1 += del_V[1]
            sum_EV_2 += del_V[2]
        for i in range(3):
            del_W = (Y[i]-o2[i])*o2[i]*(1-o2[i])

            #print("del_W", del_W)
            #print("V", V)
            #print((Y[i]-o2[i]))
            #sum_W1 = V[i]*(Y[i]-o2[i])*o2[i]*(1-o2[i])
            sum_W1 = V[i]*(Y[i]-o2[i])
            #print("sum_W1", sum_W1)
            del_W1 = -X[i]*h1[i]*(1-h1[i])*sum_W1
            #delta_W2.append(del_W2)
            #delta_W1.append(del_W1)
        print("=========================================")
        print("sum_dE/dW13", "sum_dE/dW12", "sum_dE/dW11")
        print(np.round(sum_EV_2, 4), np.round(sum_EV_1, 4), np.round(sum_EV_0, 4))
        print("=========================================")
        #print(delta_W1)

X = np.array([[1.0, 1.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [0.0, 0.0, 1.0]])
Y = np.array([0, 1, 1, 0])
network = init_network()    

In [242]:
model = model(X, network)

 <<net1>>
[[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
 <<h1>>
[[0.5077 0.5045]
 [0.5007 0.522 ]
 [0.53   0.48  ]
 [0.523  0.4975]]
 <<net2>>
[0.0782 0.079  0.0778 0.0786]
 <<o2>>
[0.5195 0.5197 0.5194 0.5196]


In [243]:
bac = backPropa(model, network)

dE/dW13 dE/dW12 dE/dW11
0.1297 0.0654 0.0658
-0.1199 -0.0626 -0.06
-0.12 -0.0576 -0.0636
0.1297 0.0645 0.0678
sum_dE/dW13 sum_dE/dW12 sum_dE/dW11
0.0196 0.0098 0.0101
dE/dW13 dE/dW12 dE/dW11
0.1297 0.0654 0.0658
-0.1199 -0.0626 -0.06
-0.12 -0.0576 -0.0636
0.1297 0.0645 0.0678
sum_dE/dW13 sum_dE/dW12 sum_dE/dW11
0.0391 0.0196 0.0202
dE/dW13 dE/dW12 dE/dW11
0.1297 0.0654 0.0658
-0.1199 -0.0626 -0.06
-0.12 -0.0576 -0.0636
0.1297 0.0645 0.0678
sum_dE/dW13 sum_dE/dW12 sum_dE/dW11
0.0587 0.0294 0.0303
dE/dW13 dE/dW12 dE/dW11
0.1297 0.0654 0.0658
-0.1199 -0.0626 -0.06
-0.12 -0.0576 -0.0636
0.1297 0.0645 0.0678
sum_dE/dW13 sum_dE/dW12 sum_dE/dW11
0.0783 0.0392 0.0403


In [284]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07], [0.092, -0.01]])
    network["V"] = np.array([0.056, 0.067, 0.016])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    #print(W, V)
    
    net1 = np.dot(x, W)
    print(" <<net1>>")
    print(np.round(net1, 4))
    h1 = sigmoid(net1)
    print(" <<h1>>")
    print(np.round(h1, 4))
    w = np.array([1.0, 1.0, 1.0, 1.0])
    w = w.reshape(-1,1)
    h1 = np.hstack((h1, w))
    net2 = np.dot(h1, V)
    print(" <<net2>>")
    print(np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    print(" <<o2>>")
    print(np.round(o2, 4))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    #print("V가중치", V)
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    delta_V = []
    delta_W = []
    #print("E/w1, E/w2, E/w3")
    sum_EV_0, sum_EV_1, sum_EV_2  = 0, 0, 0
    print("dE/dW13", "dE/dW12", "dE/dW11")
    for i in range(4):
        del_V = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
        #print(np.round(del_W2[2], 4), np.round(del_W2[1], 4), np.round(del_W2[0], 4))
            
        print(np.round(del_V[2],4), np.round(del_V[1], 4), np.round(del_V[0], 4))
        sum_EV_0 += del_V[0]
        sum_EV_1 += del_V[1]
        sum_EV_2 += del_V[2]
    for j in range(4):
            #print("del_W", del_W)
            #print("V", V)
            #print((Y[i]-o2[i]))
            #sum_W1 = V[i]*(Y[i]-o2[i])*o2[i]*(1-o2[i])
        sum_W1 = V*(Y[j]-o2[j])*o2[j]*(1-o2[j])
        
        del_W1 = -X[j]*h1[j]*(1-h1[j])*sum_W1
        
        #delta_W2.append(del_W2)
        #delta_W.append(del_W1)
        #print(delta_W)
    print("=========================================")
    print("sum_dE/dW13", "sum_dE/dW12", "sum_dE/dW11")
    print(np.round(sum_EV_2, 4), np.round(sum_EV_1, 4), np.round(sum_EV_0, 4))
    print("=========================================")
    print("sum_W1", sum_W1)
    print(del_W1)
    #print(delta_W1)

X = np.array([[1.0, 1.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [0.0, 0.0, 1.0]])
Y = np.array([0, 1, 1, 0])
network = init_network()    

In [285]:
model = model(X, network)

 <<net1>>
[[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
 <<h1>>
[[0.5077 0.5045]
 [0.5007 0.522 ]
 [0.53   0.48  ]
 [0.523  0.4975]]
 <<net2>>
[0.0782 0.079  0.0778 0.0786]
 <<o2>>
[0.5195 0.5197 0.5194 0.5196]


In [286]:
bac = backPropa(model, network)

dE/dW13 dE/dW12 dE/dW11
0.1297 0.0654 0.0658
-0.1199 -0.0626 -0.06
-0.12 -0.0576 -0.0636
0.1297 0.0645 0.0678
sum_dE/dW13 sum_dE/dW12 sum_dE/dW11
0.0196 0.0098 0.0101
sum_W1 [-0.0072638  -0.00869061 -0.00207537]
[0. 0. 0.]


In [884]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5
epoch = 10

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07]])
    network["b_W"] = np.array([[0.092, -0.01]])
    network["V"] = np.array([[0.056], [0.067]])
    network["b_V"] = np.array([[0.016]])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    
    net1 = np.dot(x, W) + b_W
    #print(" <<net1>>")
    #print(np.round(net1, 3))
    h1 = sigmoid(net1)
    #print(" <<h1>>")
    #print(np.round(h1, 3))
    net2 = np.dot(h1, V) + b_V
    #print(" <<net2>>")
    #print(np.round(net2, 3))
    h2 = sigmoid(net2)
    o2 = h2
    #print(" <<o2>>")
    #print(np.round(o2, 3))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    '''
    print(Y, Y.shape)
    print(o2, o2.shape)
    print("h1", h1, h1.shape)
    '''
    dE_dV = -(Y - o2) * o2 * (1 - o2) * h1  #h1 (4,2), -Y~~~ (4,1)
    dE_db_V = -(Y - o2) * o2 * (1 - o2)
    '''
    print(" <<dE_dV>>")
    print(np.round(dE_dV, 4))  
    print(" <<dE_db_V>>")
    print(np.round(dE_db_V, 4))
    '''
    sum_dE_dV = np.sum(dE_dV,axis=0,keepdims=True)
    sum_dE_db_V = np.sum(dE_db_V,axis=0,keepdims=True)
    '''
    print(" <<sum_dE_dV>>")
    print(np.round(sum_dE_dV, 4))
    print(" <<sum_dE_db_V>>")
    print(np.round(sum_dE_db_V, 4))
    '''
    dE_W2 = -X * h1[1] * (1-h1[1]) * (Y - o2) * o2 * (1 - o2) * V[1]
    dE_W23 = -h1[1] * (1-h1[1]) * (Y - o2) * o2 * (1 - o2) * V[1]
    sum_dE_W2 = np.sum(dE_W2,axis=0,keepdims=True)
    sum_dE_W23 = np.sum(dE_W23,axis=0,keepdims=True)
    '''
    print("  dE_W22", "  dE_W21")
    print(np.round(dE_W2, 4))
    print("  dE_W23")
    print(np.round(dE_W23[:,0].T, 4))
    print("  sum_dE_W2", "  sum_dE_W2")
    print(np.round(sum_dE_W2, 4))
    print("  sum_dE_W23", "  sum_dE_W23")
    print(np.round(sum_dE_W23[:,0], 4))
    '''
    dE_W1 = -X * h1[0] * (1-h1[0]) * (Y - o2) * o2 * (1 - o2) * V[0]
    dE_W13 = -h1[0] * (1-h1[0]) * (Y - o2) * o2 * (1 - o2) * V[0]
    sum_dE_W1 = np.sum(dE_W1,axis=0,keepdims=True)
    sum_dE_W13 = np.sum(dE_W13,axis=0,keepdims=True)
    '''
    print("  dE_W12", "  dE_W11")
    print(np.round(dE_W1, 4))
    print("  dE_W13")
    print(np.round(dE_W13[:,0].T, 4))
    print("  sum_dE_W1", "  sum_dE_W1")
    print(np.round(sum_dE_W1, 4))
    print("  sum_dE_W13")
    print(np.round(sum_dE_W13[:,0], 4))
    '''

    return sum_dE_dV, sum_dE_db_V, sum_dE_W2, sum_dE_W23[:,0], sum_dE_W1, sum_dE_W13[:,0]

def gradient_descent():            #epoch, lr, bac     
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    sum_dE_dV, sum_dE_dV13 = bac[0], bac[1] 
    sum_dE_W2, sum_dE_W23 = bac[2], bac[3]
    sum_dE_W1, sum_dE_W13 = bac[4], bac[5]
    
    print(W[0])
    print(sum_dE_W1[0])
    print(W[1])
    print(sum_dE_W2[0])
    print(b_W[0])
    print(sum_dE_W23, sum_dE_W13)
    print(V.reshape(2))
    print(sum_dE_dV[0])
    print(b_V.reshape(1))
    print(sum_dE_dV13.reshape(1))
    
    W[0] = W[0] - lr * sum_dE_W1[0]
    W[1] = W[1] - lr * sum_dE_W2[0]
    
    return W[0], W[1]
    
    '''
    print(W)
    print(V)
    print(b_W)
    print(b_V)
    print(sum_dE_dV, sum_dE_dV13)
    print(sum_dE_W2, sum_dE_W23)
    print(sum_dE_W1, sum_dE_W13)
    '''
    
    
X = np.array([[1,1],[1,0],[0,1],[0,0]])
Y = np.array([[0],[1],[1],[0]])
network = init_network()    

In [835]:
gradient_de.

In [761]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07], [0.092, -0.01]])
    network["V"] = np.array([0.056, 0.067, 0.016])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    #print(W, V)
    
    net1 = np.dot(x, W)
    print(" <<net1>>")
    print(np.round(net1, 4))
    h1 = sigmoid(net1)
    #print(" <<h1>>")
    #print(np.round(h1, 4))
    w = np.array([1.0, 1.0, 1.0, 1.0])
    w = w.reshape(-1,1)
    h1 = np.hstack((h1, w))
    print(" <<h1>>")
    print(np.round(h1, 4))
    net2 = np.dot(h1, V)
    print(" <<net2>>")
    print(np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    print(" <<o2>>")
    print(np.round(o2, 4))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    
    print(h1, h1.shape)
    A = (Y - o2) * o2 * (1 - o2)
    print(A, A.shape)
    dE_dV = -A * h1.T
    print(" <<dE_dV>>")
    print(np.round(dE_dV.T, 4))
    sum_dE_dV = np.sum(dE_dV,axis=1,keepdims=True)
    print(" <<sum_dE_dV>>")
    print(np.round(sum_dE_dV.T, 4))
    
    
    
    h1_ = np.delete(h1,[2],axis=1) 
    V_ = V[:-1]
    print("V_", V_, V_.shape)
    B = (Y - o2) * o2 * (1 - o2)
    print(V_*B)

    '''
    print("V", V, V.shape)
    B = (Y - o2) * o2 * (1 - o2)
    print("B")
    print("B", B, B.shape)
    C = X * h1 * (1 - h1)
    print("C", C, C.shape)
    print(np.dot(B, C, V))
    D = B*C.T
    print("D", D, D.shape)
    E = B*V.T
    print("E", E, E.shape)
    #sum_dv = -V * B #* V.T 
    #dE_dW = sum_dv * X * C
    #print("dE_dW")
    #print(np.round(dE_dW, 4))
    
    dE_dW1 = -(Y - o2) * o2 * (1 - o2) * V.T * h1 * (1 - h1)
    print("dE_dW1")
    print(np.round(dE_dW1, 4))
    
    dE_dW2 = -(Y - o2) * o2 * (1 - o2) * V.T
    print("dE_dW2")
    print(np.round(dE_dW2, 4))
    #dE_dW = -(Y - o2) * o2 * (1 - o2) * h1 * (1 - h1) * V
    '''
    #error_hidden_layer = d_o2.dot(V.T) # -(Y - o2) * o2 * (1 - o2) * h1 * V
    #d_hidden_layer = error_hidden_layer * sigmoid_derivative(h1) # h1 * (1 - h1)
    #print("sum_dvW", sum_dv)

    '''
    W1, W2 = network["W1"], network["W2"]
    b1, b2 = network["b1"], network["b2"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    
    for i in range(len(X)):
        del_W2 = -(Y[i]-o2[i])*o2[i]*(1-o2[i])*h1[i]
        #del_b2 = 
        print(del_W2)
    '''    
    return net1


X = np.array([[1.0, 1.0, 1.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [0.0, 0.0, 1.0]])
Y = np.array([0, 1, 1, 0])
network = init_network()    

In [573]:
model = model(X, network)

 <<net1>>
[[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
 <<h1>>
[[0.5077 0.5045 1.    ]
 [0.5007 0.522  1.    ]
 [0.53   0.48   1.    ]
 [0.523  0.4975 1.    ]]
 <<net2>>
[0.0782 0.079  0.0778 0.0786]
 <<o2>>
[0.5195 0.5197 0.5194 0.5196]


In [574]:
bac = backPropa(model, network)

[[0.50774938 0.50449988 1.        ]
 [0.50075    0.52198581 1.        ]
 [0.52996405 0.48001066 1.        ]
 [0.52298379 0.49750002 1.        ]] (4, 3)
[-0.12968867  0.11987692  0.11995575 -0.12971066] (4,)
 <<dE_dV>>
[[ 0.0658  0.0654  0.1297]
 [-0.06   -0.0626 -0.1199]
 [-0.0636 -0.0576 -0.12  ]
 [ 0.0678  0.0645  0.1297]]
 <<sum_dE_dV>>
[[0.0101 0.0098 0.0196]]
V_ [0.056 0.067] (2,)


ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [889]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5
epoch = 10

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network["W"] = np.array([[-0.089, 0.098], [0.028, -0.07]])
    network["b_W"] = np.array([[0.092, -0.01]])
    network["V"] = np.array([[0.056], [0.067]])
    network["b_V"] = np.array([[0.016]])
    
    return network

def model(x, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    
    net1 = np.dot(x, W) + b_W
    #print(" <<net1>>")
    #print(np.round(net1, 3))
    h1 = sigmoid(net1)
    #print(" <<h1>>")
    #print(np.round(h1, 3))
    net2 = np.dot(h1, V) + b_V
    #print(" <<net2>>")
    #print(np.round(net2, 3))
    h2 = sigmoid(net2)
    o2 = h2
    #print(" <<o2>>")
    #print(np.round(o2, 3))
    
    return net1, h1, net2, o2

def backPropa(model, network):
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    net1, net2 = model[0], model[2]
    h1, o2 = model[1], model[3]
    '''
    print(Y, Y.shape)
    print(o2, o2.shape)
    print("h1", h1, h1.shape)
    '''
    dE_dV = -(Y - o2) * o2 * (1 - o2) * h1  #h1 (4,2), -Y~~~ (4,1)
    dE_db_V = -(Y - o2) * o2 * (1 - o2)
    '''
    print(" <<dE_dV>>")
    print(np.round(dE_dV, 4))  
    print(" <<dE_db_V>>")
    print(np.round(dE_db_V, 4))
    '''
    sum_dE_dV = np.sum(dE_dV,axis=0,keepdims=True)
    sum_dE_db_V = np.sum(dE_db_V,axis=0,keepdims=True)
    '''
    print(" <<sum_dE_dV>>")
    print(np.round(sum_dE_dV, 4))
    print(" <<sum_dE_db_V>>")
    print(np.round(sum_dE_db_V, 4))
    '''
    dE_W2 = -X * h1[1] * (1-h1[1]) * (Y - o2) * o2 * (1 - o2) * V[1]
    dE_W23 = -h1[1] * (1-h1[1]) * (Y - o2) * o2 * (1 - o2) * V[1]
    sum_dE_W2 = np.sum(dE_W2,axis=0,keepdims=True)
    sum_dE_W23 = np.sum(dE_W23,axis=0,keepdims=True)
    '''
    print("  dE_W22", "  dE_W21")
    print(np.round(dE_W2, 4))
    print("  dE_W23")
    print(np.round(dE_W23[:,0].T, 4))
    print("  sum_dE_W2", "  sum_dE_W2")
    print(np.round(sum_dE_W2, 4))
    print("  sum_dE_W23", "  sum_dE_W23")
    print(np.round(sum_dE_W23[:,0], 4))
    '''
    dE_W1 = -X * h1[0] * (1-h1[0]) * (Y - o2) * o2 * (1 - o2) * V[0]
    dE_W13 = -h1[0] * (1-h1[0]) * (Y - o2) * o2 * (1 - o2) * V[0]
    sum_dE_W1 = np.sum(dE_W1,axis=0,keepdims=True)
    sum_dE_W13 = np.sum(dE_W13,axis=0,keepdims=True)
    '''
    print("  dE_W12", "  dE_W11")
    print(np.round(dE_W1, 4))
    print("  dE_W13")
    print(np.round(dE_W13[:,0].T, 4))
    print("  sum_dE_W1", "  sum_dE_W1")
    print(np.round(sum_dE_W1, 4))
    print("  sum_dE_W13")
    print(np.round(sum_dE_W13[:,0], 4))
    '''

    return sum_dE_dV, sum_dE_db_V, sum_dE_W2, sum_dE_W23[:,0], sum_dE_W1, sum_dE_W13[:,0]

def gradient_descent():            #epoch, lr, bac     
    W, V = network["W"], network["V"]
    b_W, b_V = network["b_W"], network["b_V"]
    sum_dE_dV, sum_dE_dV13 = bac[0], bac[1] 
    sum_dE_W2, sum_dE_W23 = bac[2], bac[3]
    sum_dE_W1, sum_dE_W13 = bac[4], bac[5]
    
    print(W[0])
    print(sum_dE_W1[0])
    print(W[1])
    print(sum_dE_W2[0])
    print(b_W[0])
    print(sum_dE_W23, sum_dE_W13)
    print(V.reshape(2))
    print(sum_dE_dV[0])
    print(b_V.reshape(1))
    print(sum_dE_dV13.reshape(1))
    
    W[0] = W[0] - lr * sum_dE_W1[0]
    W[1] = W[1] - lr * sum_dE_W2[0]
    
    return W[0], W[1]
    
    '''
    print(W)
    print(V)
    print(b_W)
    print(b_V)
    print(sum_dE_dV, sum_dE_dV13)
    print(sum_dE_W2, sum_dE_W23)
    print(sum_dE_W1, sum_dE_W13)
    '''
    
    
X = np.array([[1,1],[1,0],[0,1],[0,0]])
Y = np.array([[0],[1],[1],[0]])
network = init_network()    

In [890]:
for i in range(10):
    model = model(X, network)
    bac = backPropa(model, network)
    gradient_de = gradient_descent()

[-0.089  0.098]
[0.00013733 0.00013625]
[ 0.028 -0.07 ]
[0.00016435 0.00016271]
[ 0.092 -0.01 ]
[0.00032774] [0.00027387]
[0.056 0.067]
[0.01008531 0.00980489]
[0.016]
[0.01956666]


TypeError: 'tuple' object is not callable

In [894]:
import numpy as np 
#np.random.seed(0)

def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Input datasets
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])

epochs = 100000
lr = 0.5

inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1
'''
#Random weights and bias initialization
W = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
b_W =np.random.uniform(size=(1,hiddenLayerNeurons))
V = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
b_V = np.random.uniform(size=(1,outputLayerNeurons))

'''
#Random weights and bias initialization
W = np.array([[-0.089, 0.098], [0.028, -0.07]])
b_W = np.array([[0.092, -0.01]])
V = np.array([[0.056], [0.067]])
b_V = np.array([[0.016]])

print("Initial hidden weights: ",end='')
print(*W)
print("Initial hidden biases: ",end='')
print(*b_W)
print("Initial output weights: ",end='')
print(*V)
print("Initial output biases: ",end='')
print(*b_V)


#Training algorithm
for _ in range(epochs):
    #Forward Propagation
    net1 = np.dot(X,W)
    net1 += b_W
    #print("net1", np.round(net1, 4))
    h1 = sigmoid(net1)
    #print("h1", np.round(h1, 4))

    net2 = np.dot(h1,V)
    net2 += b_V
    #print("net2", np.round(net2, 4))
    h2 = sigmoid(net2)
    o2 = h2
    #print("o2", np.round(o2, 3))

    #Backpropagation
    dE_db_V = (Y - o2) * o2 * (1 - o2)
    dE_dV = -h1.T.dot(dE_db_V)
    sum_dE_db_V = -np.sum(dE_db_V,axis=0,keepdims=True)
    
    #print("dE_db_V", dE_db_V, dE_db_V.shape)
    #print("dE_dV", dE_dV, dE_dV.shape)
    
    dE_db_W = dE_db_V.dot(V.T) * h1 * (1 - h1)
    dE_dW = -X.T.dot(dE_db_W)
    sum_dE_db_W = -np.sum(dE_db_W,axis=0,keepdims=True)
    
    
    #print("V", V.shape)
    #print("h1.T.dot(dE_db_V)", (h1.T.dot(dE_db_V)).shape)
    #print("W", W.shape)
    #print("X.T.dot(dE_db_W)", (X.T.dot(dE_db_W)).shape)

    #Updating Weights and Biases
    V = V - dE_dV * lr
    #print("V", V)
    
    #print("b_V", b_V.shape)
    #print("sum_dE_db_V", sum_dE_db_V.shape)
    b_V = b_V - sum_dE_db_V * lr
    #print("b_V", b_V)
    W = W - dE_dW * lr
    #print("W", W)
    b_W = b_W - sum_dE_db_V * lr
    #print("b_W", b_W)

print("Final hidden weights: ",end='')
print(*W)
print("Final hidden bias: ",end='')
print(*b_W)
print("Final output weights: ",end='')
print(*V)
print("Final output bias: ",end='')
print(*b_V)

print("\nOutput from neural network after 10,000 epochs: ",end='')
print(*o2)

Initial hidden weights: [-0.089  0.098] [ 0.028 -0.07 ]
Initial hidden biases: [ 0.092 -0.01 ]
Initial output weights: [0.056] [0.067]
Initial output biases: [0.016]
Final hidden weights: [-6.55627978  7.93409101] [ 7.74838966 -6.80502434]
Final hidden bias: [-5.28492419 -5.38692419]
Final output weights: [11.48131644] [11.4064653]
Final output bias: [-5.36092419]

Output from neural network after 10,000 epochs: [0.00521456] [0.99461975] [0.99460736] [0.00660542]


In [2]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.5
iteration = 100000

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

X = np.array([[1,1],[1,0],[0,1],[0,0]])
Y = np.array([[0],[1],[1],[0]])

W = np.array([[-0.089, 0.098], [0.028, -0.07]])
b_W = np.array([[0.092, -0.01]])
V = np.array([[0.056], [0.067]])
b_V = np.array([[0.016]])

for i in range(iteration):
    net1 = np.dot(X, W) + b_W  
    h1 = sigmoid(net1)
    net2 = np.dot(h1, V) + b_V
    h2 = sigmoid(net2)
    o2 = h2
    
    dE_db_V = (Y - o2) * o2 * (1 - o2)
    sum_dE_db_V = -np.sum(dE_db_V,axis=0)   #,keepdims=True
    dE_dV = -h1*dE_db_V
    sum_dE_dV = np.dot(-h1.T, dE_db_V)
    dE_db_W = np.dot(dE_db_V, V.T) * h1 * (1 - h1)
    sum_dE_db_W = -np.sum(dE_db_W,axis=0)     #,keepdims=True
    dE_dW = -X*dE_db_W
    sum_dE_dW = -np.dot(X.T, dE_db_W)

    V = V - sum_dE_dV * lr
    b_V = b_V - sum_dE_db_V * lr 
    W = W - sum_dE_dW * lr  
    b_W = b_W - sum_dE_db_W * lr
    
    if i == 0:
        print("==net1===================")
        print(np.round(net1, 3))
        print("==h1=====================")
        print(np.round(h1, 3))
        print("==net2===================")
        print(np.round(net2, 3))
        print("==o2=====================")
        print(np.round(o2, 3))
        print("==dE/dV==================")
        print(np.round(dE_dV, 4))
        print("==dE/dVbais==================")
        print(np.round(-dE_db_V, 4))
        print("==sum(dE/dV)==================")
        print(np.round(sum_dE_dV, 4))  
        print("==sum(dE/dVbais)============")
        print(np.round(sum_dE_db_V, 4))
        print("==dE/dW============")
        print(np.round(dE_dW, 4))
        print("==dE/dWbais==================")
        print(np.round(-dE_db_W, 4))
        print("==sum(dE/dW)==================")
        print(np.round(sum_dE_dW, 4))  
        print("==sum(dE/dWbais)============")
        print(np.round(sum_dE_db_W, 4))
        print("============================")
    
    if i%1000 == 0:
        print("%d번째 o2는 :"%i, *np.round(o2, 4))

==net1===================
[[ 0.031  0.018]
 [ 0.003  0.088]
 [ 0.12  -0.08 ]
 [ 0.092 -0.01 ]]
==h1=====================
[[0.508 0.504]
 [0.501 0.522]
 [0.53  0.48 ]
 [0.523 0.498]]
==net2===================
[[0.078]
 [0.079]
 [0.078]
 [0.079]]
==o2=====================
[[0.52 ]
 [0.52 ]
 [0.519]
 [0.52 ]]
==dE/dV==================
[[ 0.0658  0.0654]
 [-0.06   -0.0626]
 [-0.0636 -0.0576]
 [ 0.0678  0.0645]]
==dE/dVbais==================
[[ 0.1297]
 [-0.1199]
 [-0.12  ]
 [ 0.1297]]
==sum(dE/dV)==================
[[0.0101]
 [0.0098]]
==sum(dE/dVbais)============
[0.0196]
==dE/dW============
[[ 0.0018  0.0022]
 [-0.0017  0.    ]
 [ 0.     -0.002 ]
 [-0.     -0.    ]]
==dE/dWbais==================
[[ 0.0018  0.0022]
 [-0.0017 -0.002 ]
 [-0.0017 -0.002 ]
 [ 0.0018  0.0022]]
==sum(dE/dW)==================
[[0.0001 0.0002]
 [0.0001 0.0002]]
==sum(dE/dWbais)============
[0.0003 0.0003]
0번째 o2는 : [0.5195] [0.5197] [0.5194] [0.5196]
1000번째 o2는 : [0.5] [0.5001] [0.4999] [0.5]
2000번째 o2는 : [0.5] [

In [998]:
import numpy as np
import matplotlib.pyplot as plt

lr = 0.7
iteration = 500000

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

X = np.array([[0.00],[0.10],[0.20],[0.30],[0.40],[0.50],[0.60],[0.70],[0.80],[0.90],[1.00]])
Y = np.array([0.00,0.36,0.64,0.84,0.96,1.00,0.96,0.84,0.64,0.36,0.00])
print("X", X.shape)
print("Y", Y.shape)
'''
W = np.random.uniform(size=(11,4))
b_W = np.random.uniform(size=(1,4))
V = np.random.uniform(size=(4,11))
b_V = np.random.uniform(size=(1,11))
'''
W = np.random.rand(11,4)
b_W = np.random.rand(1,4)
V = np.random.rand(4,11)
b_V = np.random.rand(1,11)

print(W, W.shape)
print(b_W, b_W.shape)
print(V, V.shape)
print(b_V, b_V.shape)

for i in range(iteration):
    net1 = np.dot(X.T, W) + b_W 
    h1 = sigmoid(net1)
    net2 = np.dot(h1, V) + b_V
    h2 = sigmoid(net2)
    o2 = h2
    
    dE_db_V = (Y - o2) * o2 * (1 - o2)
    sum_dE_db_V = -np.sum(dE_db_V,axis=0,keepdims=True)
    sum_dE_dV = np.dot(-h1.T, dE_db_V)
    dE_db_W = np.dot(dE_db_V, V.T) * h1 * (1 - h1)
    sum_dE_db_W = -np.sum(dE_db_W,axis=0,keepdims=True)
    sum_dE_dW = -np.dot(X, dE_db_W)

    V = V - sum_dE_dV * lr
    b_V = b_V - sum_dE_db_V * lr 
    W = W - sum_dE_dW * lr  
    b_W = b_W - sum_dE_db_W * lr
    
    if i == 0:
        print("==net1===================")
        print(np.round(net1, 3))
        print("==h1=====================")
        print(np.round(h1, 3))
        print("==net2===================")
        print(np.round(net2, 3))
        print("==o2=====================")
        print(np.round(o2, 3))
        print("==dE/dV==================")
        print(np.round(dE_dV, 4))
        print("==dE/dVbais==================")
        print(np.round(-dE_db_V, 4))
        print("==sum(dE/dV)==================")
        print(np.round(sum_dE_dV, 4))  
        print("==sum(dE/dVbais)============")
        print(np.round(sum_dE_db_V, 4))
        print("==dE/dW============")
        print(np.round(dE_dW, 4))
        print("==dE/dWbais==================")
        print(np.round(-dE_db_W, 4))
        print("==sum(dE/dW)==================")
        print(np.round(sum_dE_dW, 4))  
        print("==sum(dE/dWbais)============")
        print(np.round(sum_dE_db_W, 4))
        print("============================")
    
    if i%2000 == 0:
        print("%d번째 o2는 :"%i, *np.round(o2, 4))


X (11, 1)
Y (11,)
[[0.6694618  0.14751074 0.21920035 0.11873554]
 [0.81364196 0.95003571 0.185637   0.28916376]
 [0.34761842 0.4987802  0.40862292 0.99032858]
 [0.63101294 0.92579005 0.83368365 0.50226207]
 [0.6589473  0.55432561 0.05055241 0.03613047]
 [0.29494474 0.2282115  0.76242654 0.65456042]
 [0.55283573 0.1380606  0.53965185 0.59041259]
 [0.61081632 0.21996844 0.88105233 0.10427307]
 [0.44419226 0.55161559 0.37354375 0.57273889]
 [0.89549328 0.48546047 0.81550294 0.36266793]
 [0.58761079 0.09290527 0.22877432 0.74827948]] (11, 4)
[[0.20832428 0.45841595 0.29524552 0.15002805]] (1, 4)
[[0.79080853 0.74670427 0.5199104  0.29588715 0.69327749 0.66350007
  0.54652451 0.98468537 0.38209986 0.98993765 0.16438732]
 [0.1985356  0.06183668 0.38200482 0.31741168 0.51680949 0.98719422
  0.16201327 0.90604806 0.25532738 0.60146345 0.46434893]
 [0.81170381 0.68136829 0.52269384 0.7915728  0.80068891 0.10380742
  0.15135342 0.58837262 0.45836282 0.10790436 0.1798393 ]
 [0.07687244 0.84945999

118000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
120000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
122000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
124000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
126000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
128000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
130000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
132000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
134000번째 o2는 : [0.0011 0.36   0.64   0.84   0.96   0.9989 0.96   0.84   0.64   0.36
 0.0011]
136000번째 o2는 : [0.001 0.36  0.64  0.84  0.96  0.999 0.96  0.84  0.64  0.36  0.001]
138000번째 o2는 : [0.001 0.36  0.64  0.84  0.96  0.999 0.96  0.84  0.64  0.36  0.00

262000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 8.000e-04]
264000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
266000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
268000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
270000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
272000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
274000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 7.000e-04]
276000번째 o2는 : [7.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.993e-01 9.600e-01
 8.400e-01 6.400e-

394000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
396000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
398000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
400000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
402000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
404000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
406000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-01 3.600e-01 6.000e-04]
408000번째 o2는 : [6.000e-04 3.600e-01 6.400e-01 8.400e-01 9.600e-01 9.994e-01 9.600e-01
 8.400e-01 6.400e-

In [3]:
?np.sum