In [1]:
import tensorflow as tf

C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1)

## Graph and Session
TensorFlow는 Data Flow 그래프를 사용하여 개별 작업 간의 종속성 측면에서 계산을 표현한다. 따라서 Data Flow 그래프를 먼저 정의한 다음 TensorFlow Session을 생성하여 로컬 및 원격 장치 집합에 걸쳐 그래프의 일부를 실행한다.

![image](https://www.tensorflow.org/images/tensors_flowing.gif)

## Tensor

Tensor란 다차원 행렬이다. NumPy ndarray 객체와 유사하게 Tensor 객체는 데이터 유형과 형태를 가지고 있다. 또한 Tensor는 가속기(GPU와 같은) 메모리에 상주할 수 있다. 텐서플로우는 Tensor를 소비하고 생산하는 풍부한 운영 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등)를 제공한다. 이러한 작업은 네이티브 Python 유형을 자동으로 변환한다.

### Tensors are not evaluated immediately.

In [3]:
a = tf.Variable(1)
print(a)
b = tf.constant(1)
print(b)
print(a+b)

<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>
Tensor("Const:0", shape=(), dtype=int32)
Tensor("add:0", shape=(), dtype=int32)


바로 출력되지 않고 tensor에 구조화만 한다.

### Building a Graph

대부분의 텐서플로우 프로그램은 Data flow 그래프 구조화하는 단계로 시작한다. 이 단계에서는 새로운 tf.Operation(노드) 및 tf.Tensor(에지) 객체를 생성하여 tf.Graph instance에 추가하는 TensorFlow API 기능을 호출한다. TensorFlow는 동일한 맥락에서 모든 API 함수에 대한 암시적 인수인 기본 그래프를 제공한다. 즉 tensorflow를 호출하면 tensor를 구조화하는 graph(그림을 그리는 도화지?)를 기본적(default_graph)으로 만든다. 우리는 그 도화지에다 tensor를 그리는 것이다.

In [4]:
c = tf.constant(4.0)

c.graph is tf.get_default_graph()

True

또 다른 일반적인 사용법에는 tf.Graph.as_default를 통해서 새로운 graph(도화지)를 재생성(g)한다.

In [5]:
g = tf.Graph()
with g.as_default():
    # Define operations and tensors in 'g'.
    c = tf.constant(30.0)
    print(c.graph is g)

True


### Executing a graph in a tf.Session

TensorFlow는 tf.Session 클래스를 사용하여 클라이언트 프로그램(일반적으로 파이선 프로그램)과 C++ 런타임 간의 연결을 나타낸다. tf.Session 객체는 로컬 시스템의 장치와 분산된 TensorFlow 런타임을 사용하는 원격 장치에 대한 액세스를 제공한다. 또한 동일한 계산을 여러 번 효율적으로 실행할 수 있도록 tf.Graph에 대한 정보를 캐시한다.

### Using tf.Session.run to execute operations

tf.Session_run 방법은 tf.Operation을 실행하거나 tf.Tensor를 평가하기 위한 주요 메커니즘이다. 하나 이상의 tf.Operation 또는 tf.Tensor 개체를 tf.Session.run에 전달할 수 있으며, TensorFlow는 결과를 계산하는 데 필요한 작업을 실행한다.

In [6]:
a = tf.constant(1.0)
b = tf.constant(2.0)

sess = tf.Session()
print(sess.run(a+b))
sess.close()

3.0


tf.Session.run()으로 그래프(도화지)에 그린 a, b 개체를 실행할 수 있다.

In [7]:
a = tf.constant(1.0)
b = tf.constant(2.0)

with tf.Session() as sess:
    print(sess.run(a+b))

3.0


### tf.placeholder

**중요**: 이 텐서는 평가하면 **오류**를 발생시킨다. 해당 값은 Session.run()에 대한 feed_dict 옵션 인수를 사용하여 입력해야 한다.

In [9]:
# error
x = tf.placeholder(tf.float32)
with tf.Session() as sess:
    sess.run(x)

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[node Placeholder (defined at <ipython-input-9-7824aa4eb3d8>:2) ]]

Caused by op 'Placeholder', defined at:
  File "C:\Anaconda3\envs\nlp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\nlp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Anaconda3\envs\nlp\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\kernelapp.py", line 563, in start
    self.io_loop.start()
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Anaconda3\envs\nlp\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "C:\Anaconda3\envs\nlp\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "C:\Anaconda3\envs\nlp\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3242, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-7824aa4eb3d8>", line 2, in <module>
    x = tf.placeholder(tf.float32)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5790, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Anaconda3\envs\nlp\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[node Placeholder (defined at <ipython-input-9-7824aa4eb3d8>:2) ]]


In [10]:
x = tf.placeholder(tf.float32)
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x:0.0}))

0.0


tf.placeholder를 정의할 때 tf.Seesion().run() 할 때, feed_dict으로 x를 정의해 준다.

## tf.Tensor - revisited

텐서란 다차원 배열이다. NumPy ndarray 객체와 유사하게 텐서 객체는 데이터 유형과 형태를 가지고 있다. 또한 텐서는 가속기(GPU와 같은) 메모리에 상주할 수 있다. 텐서플로우(TensorFlow)는 텐서를 소비하고 생산하는 풍부한 운영 라이브러리(tf_add, tf_matmul, tf_linalg.inv 등)를 제공한다. 이러한 작업은 네이티브 Python 유형을 자동으로 변환한다.

In [11]:
import numpy as np

In [13]:
with tf.Session() as sess:
    constant_a = tf.constant(1.0)
    print(constant_a)
    print(sess.run(constant_a))
    
    constant_b = tf.constant([[1.0,2.0],
                             [3.0,4.0]])
    print(constant_b)
    print(sess.run(constant_b))
    
    constant_c = tf.constant([1.0,2.0,3.0,4.0])
    print(constant_c)
    print(sess.run(constant_c))
    
    constant_d = tf.constant([1.0,2.0,3.0,4.0], shape=[2,2])
    print(constant_d)
    print(sess.run(constant_d))
    
    constant_e = tf.constant(1.0, shape=(2,3))
    print(constant_e)
    print(sess.run(constant_e))

Tensor("Const_6:0", shape=(), dtype=float32)
1.0
Tensor("Const_7:0", shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]
Tensor("Const_8:0", shape=(4,), dtype=float32)
[1. 2. 3. 4.]
Tensor("Const_9:0", shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]
Tensor("Const_10:0", shape=(2, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
with tf.Session() as sess:
    a = tf.constant([[1.0,0.0],
                    [0.0,1.0]])
    b = a+1
    print(a)
    print(b)
    print(a*b)
    print(sess.run(a*b))
    print(tf.matmul(a,b))
    print(sess.run(tf.matmul(a,b)))
    
    c = np.multiply(a, b)
    print(c)
    print(sess.run(c))

Tensor("Const_11:0", shape=(2, 2), dtype=float32)
Tensor("add_3:0", shape=(2, 2), dtype=float32)
Tensor("mul:0", shape=(2, 2), dtype=float32)
[[2. 0.]
 [0. 2.]]
Tensor("MatMul:0", shape=(2, 2), dtype=float32)
[[2. 1.]
 [1. 2.]]
Tensor("mul_2:0", shape=(2, 2), dtype=float32)
[[2. 0.]
 [0. 2.]]


### tf.Variable - Variables should be initialized.
tf.Variable을 정의하면 초기화를 반드시 시켜야 한다.

In [15]:
x = tf.Variable(1)
with tf.Session() as sess:
    print(sess.run(x))

FailedPreconditionError: Attempting to use uninitialized value Variable_2
	 [[{{node _retval_Variable_2_0_0}}]]

In [16]:
x = tf.Variable(1)
with tf.Session() as sess:
    sess.run(x.initializer)
    print(sess.run(x))

1


In [17]:
x = tf.Variable(1)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

1


### Performance

In [19]:
import time

def measure(x, steps):
    # Tensorflow initializes a GPU the first time it's used, exclude from timing.
    with tf.Session() as sess:
        sess.run(tf.matmul(x, x))
        
        start = time.time()
        for i in range(steps):
            x = tf.matmul(x, x)
        _ = sess.run(x)
        end = time.time()
    return end - start

shape = (10000, 10000)
steps = 10
print("Time to multiply a {} matrix by itself {} times".format(shape, steps))

# Run on CPU
with tf.device("/cpu:0"):
    print("CPU: {} secs".format(measure(tf.random_normal(shape), steps)))
    
# Run on GPU, if available:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        print("GPU: {} secs".format(measure(tf.random_normal(shape), steps)))
else:
    print("GPU: not found")

Time to multiply a (10000, 10000) matrix by itself 10 times
CPU: 372.8957567214966 secs
GPU: not found


## Computing gradients

Automatic differentiation는 신경망 훈련을 위한 backpropagation과 같은 기계학습 알고리즘을 구현하는데 유용하다. tf.GradientTape를 사용하여 나중에 computing gradients을 위한 작업을 사용한다.

### tf.GradientTape

Operations은 이 컨텍스트 관리자 내에서 실행되고 입력 사항 중 적어도 하나가 "watched"되고 있는 경우에 기록된다.

Trainable 가능한 변수(tf.Varible 또는 tf.get_varible로 생성됨, 여기서 trainable=True는 두 경우 모두 기본값이다)가 자동으로 감시된다. 이 컨텍스트 매니저에서 watch method를 호출하여 Tensors를 수동으로 감시할 수 있다.

예를 들어, consider the function y = x * x. The gradient at x = 3.0 can be computed as:

In [20]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = x * x
dy_dx = g.gradient(y, x)   # 6.0으로 계산될 것임

with tf.Session() as sess:
    print(sess.run(dy_dx))

6.0


In [22]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = 1
    for i in range(3):
        y *= x
dy_dx = g.gradient(y, x)

with tf.Session() as sess:
    print( sess.run(dy_dx) )

27.0


In [25]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = 1
    for i in range(3):
        if i < 2:
            y *= x
        else:
            y += x
dy_dx = g.gradient(y, x)

with tf.Session() as sess:
    print( sess.run(dy_dx) )

7.0


In [30]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    with tf.GradientTape() as gg:
        gg.watch(x)
        y = x * x
    dy_dx = gg.gradient(y, x)
dy2_dx2 = g.gradient(dy_dx, x)

with tf.Session() as sess:
    print( sess.run(dy_dx) )
    print( sess.run(dy2_dx2) )

6.0
2.0
